### ISSUE TITLE
« Quiz » 6

### ISSUE THREAD

**Issue by ThomasGareau** [ThomasGareau/github-slideshow#4]
![Gif Quiz 6](https://media.giphy.com/media/xUPGcnhop8QD7HHztS/giphy.gif)
@samGuay

**Comment by SamGuay** [comment]
Allô Thomas! 

Réfère-toi à la section sur [comment insérer une image en Markdown](https://guides.github.com/features/mastering-markdown/) et ton GIF devrait apparaitre! :smile:

**Comment by ThomasGareau** [comment]
Oups! Est ce que tu reçois des modifications à chaque fois que je modifie? 

Désolé!!

**Comment by SamGuay** [comment]
Ahah, non, inquiète-toi pas pour ça! J'ai juste reçu un courriel pour le @SamGuay. C'est bien que tu aies découvert la fonction _Edit_ cependant!

**Comment by ThomasGareau** [comment]
Ahhh fiou! Merci pour l'aide, j'ai sélectionné mon gif avec beaucoup d'attention! Et je suis effectivement devenu un maître de la fonction "edit" 😁
